version: '3.8'
services:
  db:
    container_name: employee_app
    image: mysql:8.0
    restart: "no"
    environment:
      MYSQL_DATABASE: employee-db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - employee-data:/var/lib/mysql
volumes:
  employee-data:
