version: '3.8'
services:
  db:
    image: mysql:8
    restart: "no"
    container_name: employee-db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: dbuser
      MYSQL_DATABASE: guest-app
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
